### PR TITLE
Add workers middleware and reengineer diesel middleware to make use of it

### PR DESCRIPTION
**Pull request by smangelsdorf**
The best (read: laziest) way to describe this PR is by pointing at the documentation for the "workers" and "diesel" middleware as written for this PR (mostly the rustdoc).

Ref #210

### CODE REVIEW

**Comment by smangelsdorf** [comment]
Ah, needs a rebase to work with Gotham `master`

**Comment by whitfin** [comment]
@smangelsdorf by any chance, do you want to finish this up? I think the workers middleware might be a good thing to ship alongside `gotham` itself, rather than being separated - we could maybe make use of it internally that way (and other people can work with it more easily).

**Comment by smangelsdorf** [comment]
Sure, will do. I kept it separate while it was an experiment but I'm happy to move it into the main Gotham codebase.

**Comment by smangelsdorf** [comment]
@im-0: Thanks, that sorted it 👍

**Comment by smangelsdorf** [comment]
I still plan to sort out the reduced coverage and the new merge conflict, just haven't got to it yet.

**Comment by smangelsdorf** [comment]
The changes here aren't compatible anymore with the `master` branch. The amount of work required to fix it probably warrants being submitted as a new PR (including weighing up whether the approach I took is still the correct one given the ecosystem as it exists now). I'm going to close this PR but leave the branch intact in case somebody wants to pick it up and continue working on it.

Recent releases of Rust may also allow some better refactoring, especially `impl Trait` which I note I've previously left a TODO comment about.

**Comment by whitfin** [comment]
@smangelsdorf noted - I'll take a look and it and see if I can get your work into master, to avoid having you wasted your time

**Comment by smangelsdorf** [comment]
The time is a sunk cost at this point, so don't worry about wasting it 😉 

Hopefully some percentage of this is still useful in the new world of Tokio/Futures/Hyper, but if it's easier to throw it out and redo it differently I won't take it to heart.

**Comment by colinbankier** [comment]
@whitfin - I'm interested in seeing if I can resurrect this. I don't want to double up however, if you've already got far with it.

**Pull request closed without merging**
