### PR TITLE
Refactor TestServer API

### LINKED ISSUE #16: Improve TestServer API
The 0.1 API for `TestServer` is a pretty rough, early version. Due to the way we're handling connections internally and allowing _everything_ to be configured, there are a lot of arbitrary variables being set by test cases when they could be defaulted and only overridden when the need arises.

This ticket is mostly a "go back and reduce the boilerplate for integration tests" ticket.

The way a test HTTP client is created and used seems like an obvious target.

### PR DESCRIPTION
**Pull request by smangelsdorf**
The big pieces here:

* Retain the client address in `State` - it was previously available via `Request`, but after #45 we're no longer able to access it
* Refactor `TestServer` to take a `NewHandler` (most commonly this will be a `Router`) instead of a `NewService`. Previously, the test case needed to wrap its own handler in `NewHandlerService`
* Reduce the boilerplate needed to use `TestServer`, and make the API a little more intuitive

Before:

```rust
let new_service = NewHandlerService::new(router);
let mut test_server = TestServer::new(new_service).unwrap();
let client = test_server
    .client("127.0.0.1:10000".parse().unwrap())
    .unwrap();
let uri = "http://example.com/".parse().unwrap();
let response = test_server.run_request(client.get(uri)).unwrap();
assert_eq!(response.status(), StatusCode::Ok);
assert_eq!(
    test_server.read_body(response).unwrap(),
    b"Hello, world!"
);
```

After:

```rust
let test_server = TestServer::new(router).unwrap();
let response = test_server.client().get("http://example.com/").perform().unwrap();
assert_eq!(response.status(), StatusCode::Ok);
assert_eq!(response.read_body().unwrap(), b"Hello, world!");
```

Fixes #16

### CODE REVIEW

**Comment by smangelsdorf** [comment]
Hold this, pending outcomes of discussion in #14

**Comment by bradleybeddoes** [comment]
Are we still holding pending https://github.com/gotham-rs/gotham/issues/14 ?

**Comment by smangelsdorf** [comment]
Yes. Sorry, I've been waylaid by other work and this still needs to be sorted out.

**Comment by smangelsdorf** [comment]
@chklauser: I've added some changes in here that you suggested in #14. If you have time to look at them, I'd appreciate any further suggestions or comments.

**Pull request merged**
