### PR TITLE
Implement run_until() similar to hyper's run_until()

### PR DESCRIPTION
**Pull request by im-0**
This adds the ability to gracefully shut down the event loop using special signaling future.

Fixes gotham-rs/gotham#220.

### CODE REVIEW

**Comment by bradleybeddoes** [comment]
I've kicked it over again, likely a temp fault on their side.

**Comment by im-0** [comment]
I'll rebase this...

**Comment by im-0** [comment]
Changes:

* Rebased on master.
* Added usage example.

`cargo fmt` will fail because of newer rustfmt shipped with new stable rust.

**Comment by smangelsdorf** [comment]
CI failure seems to be caused by one of the `run_until` tests from the example app not terminating.

```
Launching test
running /home/travis/build/gotham-rs/gotham/target/debug/deps/gotham_examples_hello_world_until-431af34fac0cc11d

running 2 tests
Code is mulithreaded, disabling hit count
.Listening for requests at http://127.0.0.1:7878
Press Ctrl+C to exit
```

**Comment by im-0** [comment]
@smangelsdorf I believe that this happens because `tarpaulin` are not forwarding "unexpected" signals by default. See last commit (`Add option "--forward" to tarpaulin.`).

I am not sure why Travis-CI used old script (without --forward).

**Comment by im-0** [comment]
Closing this in favor of gotham-rs/gotham#249.

**Pull request closed without merging**
