### PR TITLE
Rename gotham::http to gotham::protocol

### PR DESCRIPTION
**Pull request by ChristophWurst**
This prevents naming conflicts of the `http` crate used in Hyper 0.12.

As [suggested](https://github.com/gotham-rs/gotham/issues/165#issuecomment-382529429) by @smangelsdorf, I chose `protocol` as the new module name.

There were 6 doc tests that failed locally. Errors like this one popped up, although I fixed `gotham_derive`:

```
---- src/router/builder/single.rs - router::builder::single::DefineSingleRoute::with_query_string_extractor (line 243) stdout ----
        error[E0433]: failed to resolve. Could not find `http` in `gotham`
  --> src/router/builder/single.rs:261:34
   |
19 | #[derive(StateData, Deserialize, StaticResponseExtender)]
   |                                  ^^^^^^^^^^^^^^^^^^^^^^ Could not find `http` in `gotham`
```

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> There were 6 doc tests that failed locally.

They fail on Travis as well. I still don't know where the old `http` module is referenced at.
```
failures:
    src/extractor/path.rs - extractor::path::PathExtractor (line 21)
    src/extractor/query_string.rs - extractor::query_string::QueryStringExtractor (line 21)
    src/router/builder/mod.rs - router::builder::AssociatedRouteBuilder<'a, C, P, PE, QSE>::with_path_extractor (line 348)
    src/router/builder/mod.rs - router::builder::AssociatedRouteBuilder<'a, C, P, PE, QSE>::with_query_string_extractor (line 409)
    src/router/builder/single.rs - router::builder::single::DefineSingleRoute::with_path_extractor (line 174)
    src/router/builder/single.rs - router::builder::single::DefineSingleRoute::with_query_string_extractor (line 243)
```

**Comment by whitfin** [comment]
@ChristophWurst small note, I added another example recently in https://github.com/gotham-rs/gotham/pull/215. Can you please grab the `gotham::http` in that example too?

**Comment by bradleybeddoes** [comment]
> Incidentally, your issue with those tests is because the repository gotham points at the published 0.2 of gotham_derive, not the version in the repo (for whatever reason).

Good catch, it shouldn't be, leftover from our migration to a single workspace. [This is a bug](https://github.com/gotham-rs/gotham/blob/master/gotham/Cargo.toml#L36) that can get sorted as part of this PR if you wouldn't mind @ChristophWurst.

**Comment by ChristophWurst** [comment]
Fixed :rocket:

**Comment by bradleybeddoes** [comment]
@smangelsdorf and I have been talking about naming offline (I was late to this entire discussion).

I felt like `gotham::protocol::{request, response, header}` wasn't the best naming, as in which protocol are we referring to? This confusion would be compounded when Gotham does something with WebSockets.

I believe we arrived at changing `gotham::http`/`gotham::protocol` to `gotham::helpers::http` which was inspired by the existing [module comment](https://github.com/gotham-rs/gotham/blob/master/gotham/src/http/mod.rs#L1) and to my mind properly describes what the code here does. As part of this `{request, response, header}` components would be re-exported under `gotham::helpers::http` keeping #71 in mind.

Thoughts?

**Comment by smangelsdorf** [comment]
> I believe we arrived at changing `gotham::http`/`gotham::protocol` to `gotham::helpers::http`

Yep, that's where we got to.

**Pull request merged**
