### PR TITLE
Update diesel to 2.0

### PR DESCRIPTION
**Pull request by msrd0**

### CODE REVIEW

**Review by nyarly — APPROVED** [review]
:+1: We'll need to consider semver on this

**Comment by msrd0** [comment]
> We'll need to consider semver on this

diesel is a public dependency of the diesel middleware so this is definitely a breaking change

**Comment by svenfoo** [comment]
Is there a plan to get this merged? Just finished porting the ORM parts of a project to diesel-2.0 only to find out that ` gotham_middleware_diesel` isn't compatible with it yet.  Would be awesome to get this merged and released soon.

**Comment by msrd0** [comment]
@svenfoo I think my plan was to migrate my server code to diesel 2.0 and test these changes before I merge and release them, but that never happened. Given that the changes seems rather simple and we have tests, it's probably ok to merge this anyways.

**Pull request merged**
