### PR TITLE
Support graceful shutdown.

### PR DESCRIPTION
**Pull request by im-0**
This is a version of gotham-rs/gotham#223 updated for the current `master` branch.

Fixes gotham-rs/gotham#220.

### CODE REVIEW

**Comment by whitfin** [comment]
@im-0 I'm not sure I understand exactly what this adds... the ability to CTRL+C without killing the application itself? Can you just brief me real quick? I ask because I saw `run_until` references but they don't seem to be involved here.

**Comment by im-0** [comment]
@whitfin, in general, this adds a way to programmatically stop the running Gotham server. May be used to perform deinitialization when stopping the server (something more complex than just "kill the process").

> I ask because I saw run_until references but they don't seem to be involved here.

Previous version (see gotham-rs/gotham#223) was designed to be similar to the [run_until() from hyper 0.11](https://docs.rs/hyper/0.11.27/hyper/server/struct.Server.html#method.run_until). But as 1) this function was removed from hyper 0.12 and 2) Gotham code was also changed heavily during migration to new `tokio`, I made this new set of patches. New solution is much simpler.

**Comment by im-0** [comment]
(rebased onto current master)

**Comment by colinbankier** [comment]
Thanks - this looks good to me :+1: 
Just thinking out load, I was wondering if the dance to set up the signal etc could be included in `gotham/src/lib.rs` so that it could be re-used rather then each app setting it up - and maybe exposed in a way you could pass a closure in for the shutdown hook. Not really necessary - just a thought.

**Comment by im-0** [comment]
@whitfin will do.

**Comment by nyarly** [comment]
@im-0 Checking in - if I understand your change correctly, the actual Gotham code is superseded by #254, but the example code looks great. Are you still willing to update the example against init_server?

**Comment by ravernkoh** [comment]
Would love this to be merged!

**Comment by nyarly** [comment]
I've submitted #310 to get this example merged. Thank you, @im-0 for you work on this.

@ravernkoh The feature itself is already present in Gotham as it ships today. The example as presented in #310 illustrates how to do that.

**Comment by ravernkoh** [comment]
Thanks @nyarly. Although I feel the issue should only be closed when the PR is merged.

**Pull request closed without merging**
